import os
import pymongo

# Automatically read your cloud network access credentials out of your .env file
mongo_uri = None
if os.path.exists(".env"):
    with open(".env", "r") as file:
        for line in file:
            if "MONGO_URI" in line or "MONGO_URL" in line:
                mongo_uri = line.split("=", 1)[1].strip().strip('"').strip("'")

if not mongo_uri:
    print("⚠️ Could not read MONGO_URI from your local configuration.")
    mongo_uri = input("Please manually paste your MongoDB Atlas Connection String: ").strip()

try:
    print("🔌 Opening data pipeline to MongoDB Atlas Cloud Cluster...")
    client = pymongo.MongoClient(mongo_uri)
    db = client["library"] 
    books_collection = db["Book"]

    print("🗑️ Wiping old database entries for a perfectly clean slate...")
    books_collection.delete_many({})

    print("📦 Packing exactly 100 premium book volumes into the database matrix...")
    master_book_list = [
      # === FANTASY (5 Books) ===
      {"title": "The Hobbit", "author": "J.R.R. Tolkien", "category": "Fantasy", "isbn": "9780261103283", "available": 5, "description": "Bilbo Baggins lives a quiet life until the wizard Gandalf and a company of dwarves whisk him away.", "image_url": "https://covers.openlibrary.org/b/isbn/9780261103283-L.jpg", "price": 14.99, "rating": 4.9, "queue_list": []},
      {"title": "A Game of Thrones", "author": "George R.R. Martin", "category": "Fantasy", "isbn": "9780553573404", "available": 3, "description": "In a land where summers can last decades and winters a lifetime, noble houses fight for control.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg", "price": 18.95, "rating": 4.7, "queue_list": []},
      {"title": "The Way of Kings", "author": "Brandon Sanderson", "category": "Fantasy", "isbn": "9780765365279", "available": 4, "description": "On a world scarred by storms, a slave medic and an aging warlord hold secrets to an ancient order.", "image_url": "https://covers.openlibrary.org/b/isbn/9780765365279-L.jpg", "price": 21.99, "rating": 4.9, "queue_list": []},
      {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "category": "Fantasy", "isbn": "9780756404741", "available": 2, "description": "The riveting first-person account of Kvothe, a notoriously gifted wizard, musician, and king-killer.", "image_url": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg", "price": 15.99, "rating": 4.8, "queue_list": []},
      {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "category": "Fantasy", "isbn": "9780590353428", "available": 8, "description": "An orphaned young boy discovers he has inherited grand magical abilities and an invitation to Hogwarts.", "image_url": "https://covers.openlibrary.org/b/isbn/9780590353428-L.jpg", "price": 12.99, "rating": 4.9, "queue_list": []},

      # === SCI-FI (10 Books) ===
      {"title": "Dune", "author": "Frank Herbert", "category": "Sci-Fi", "isbn": "9780441172719", "available": 6, "description": "Set on a desert planet, Paul Atreides must navigate betrayal to control the universe's spice resource.", "image_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg", "price": 16.99, "rating": 4.8, "queue_list": []},
      {"title": "Neuromancer", "author": "William Gibson", "category": "Sci-Fi", "isbn": "9780441569595", "available": 3, "description": "The definitive cyberpunk novel tracking a matrix-hacker hired for an impossible run against an AI.", "image_url": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg", "price": 13.50, "rating": 4.6, "queue_list": []},
      {"title": "Foundation", "author": "Isaac Asimov", "category": "Sci-Fi", "isbn": "9780553293357", "available": 4, "description": "As a grand galactic empire collapses, scientists utilize mathematics to preserve human knowledge.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg", "price": 11.99, "rating": 4.7, "queue_list": []},
      {"title": "Project Hail Mary", "author": "Andy Weir", "category": "Sci-Fi", "isbn": "9780593135204", "available": 2, "description": "The sole survivor of a desperate mission must use his skills to save Earth from a solar parasite.", "image_url": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg", "price": 22.00, "rating": 4.9, "queue_list": []},
      {"title": "The Martian", "author": "Andy Weir", "category": "Sci-Fi", "isbn": "9780553418026", "available": 3, "description": "Stranded on Mars by an unexpected dust storm, astronaut Mark Watney must engineer a way to survive.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg", "price": 14.99, "rating": 4.8, "queue_list": []},
      {"title": "Snow Crash", "author": "Neal Stephenson", "category": "Sci-Fi", "isbn": "9780441001422", "available": 4, "description": "A high-speed cyber-thriller exploring virtual reality, corporate franchises, and a deadly digital virus.", "image_url": "https://covers.openlibrary.org/b/isbn/9780441001422-L.jpg", "price": 15.99, "rating": 4.6, "queue_list": []},
      {"title": "Brave New World", "author": "Aldous Huxley", "category": "Sci-Fi", "isbn": "9780060850524", "available": 5, "description": "A chilling vision of a highly mechanized, genetically engineered utopian society based on consumption.", "image_url": "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg", "price": 12.99, "rating": 4.7, "queue_list": []},
      {"title": "Fahrenheit 451", "author": "Ray Bradbury", "category": "Sci-Fi", "isbn": "9781451673319", "available": 6, "description": "In a dystopian future where books are banned and burned, one fireman begins to question his mission.", "image_url": "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg", "price": 11.50, "rating": 4.8, "queue_list": []},
      {"title": "The Left Hand of Darkness", "author": "Ursula K. Le Guin", "category": "Sci-Fi", "isbn": "9780441478125", "available": 3, "description": "A human envoy visits an icy planet inhabited by an ambisexual species to broker an interstellar alliance.", "image_url": "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg", "price": 14.00, "rating": 4.7, "queue_list": []},
      {"title": "Ender's Game", "author": "Orson Scott Card", "category": "Sci-Fi", "isbn": "9780765342294", "available": 5, "description": "A brilliant young boy is recruited into an orbital military academy to train for an alien fleet war.", "image_url": "https://covers.openlibrary.org/b/isbn/9780765342294-L.jpg", "price": 13.99, "rating": 4.8, "queue_list": []},

      # === HORROR (12 Books) ===
      {"title": "The Shining", "author": "Stephen King", "category": "Horror", "isbn": "9780345806789", "available": 4, "description": "Jack Torrance takes a winter caretaker position at a hotel, unaware that supernatural forces inhabit it.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345806789-L.jpg", "price": 16.99, "rating": 4.8, "queue_list": []},
      {"title": "Dracula", "author": "Bram Stoker", "category": "Horror", "isbn": "9780486411095", "available": 5, "description": "The gothic classic detailing an ancient vampire's voyage to Victorian England to spread his unholy curse.", "image_url": "https://covers.openlibrary.org/b/isbn/9780486411095-L.jpg", "price": 9.99, "rating": 4.6, "queue_list": []},
      {"title": "Frankenstein", "author": "Mary Shelley", "category": "Horror", "isbn": "9780486282114", "available": 3, "description": "A brilliant obsession turns to horror when a scientist synthesizes conscious life from dead tissue.", "image_url": "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg", "price": 8.50, "rating": 4.5, "queue_list": []},
      {"title": "It", "author": "Stephen King", "category": "Horror", "isbn": "9781501142970", "available": 1, "description": "Seven childhood friends confront a shape-shifting predator that emerges from the sewers of Derry.", "image_url": "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg", "price": 19.99, "rating": 4.8, "queue_list": []},
      {"title": "Misery", "author": "Stephen King", "category": "Horror", "isbn": "9781501156748", "available": 2, "description": "A famous novelist is rescued from a car crash by his number one fan, who turns out to be unstable.", "image_url": "https://covers.openlibrary.org/b/isbn/9781501156748-L.jpg", "price": 15.99, "rating": 4.7, "queue_list": []},
      {"title": "Pet Sematary", "author": "Stephen King", "category": "Horror", "isbn": "9781439150931", "available": 4, "description": "A doctor discovers a mysterious burial ground hidden deep within the woods that holds the power of resurrection.", "image_url": "https://covers.openlibrary.org/b/isbn/9781439150931-L.jpg", "price": 16.99, "rating": 4.9, "queue_list": []},
      {"title": "Salem's Lot", "author": "Stephen King", "category": "Horror", "isbn": "9780307743671", "available": 3, "description": "A writer returns home to confront childhood fears, only to discover an ancient vampire evil has arrived.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307743671-L.jpg", "price": 14.95, "rating": 4.8, "queue_list": []},
      {"title": "The Haunting of Hill House", "author": "Shirley Jackson", "category": "Horror", "isbn": "9780143039983", "available": 4, "description": "Four paranormal seekers stay at a notorious, morphing house, triggering deep psychological horror.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143039983-L.jpg", "price": 13.99, "rating": 4.7, "queue_list": []},
      {"title": "The Exorcist", "author": "William Peter Blatty", "category": "Horror", "isbn": "9780061007224", "available": 2, "description": "The terrifying clinical timeline of an eleven-year-old girl possessed by an ancient demonic presence.", "image_url": "https://covers.openlibrary.org/b/isbn/9780061007224-L.jpg", "price": 14.99, "rating": 4.6, "queue_list": []},
      {"title": "Bird Box", "author": "Josh Malerman", "category": "Horror", "isbn": "9780062259653", "available": 3, "description": "A mother floats down a dangerous river blindfolded with two kids to escape invisible entities that drive people mad.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062259653-L.jpg", "price": 13.50, "rating": 4.4, "queue_list": []},
      {"title": "Heart-Shaped Box", "author": "Joe Hill", "category": "Horror", "isbn": "9780061914171", "available": 3, "description": "An aging rockstar buys a dead man's suit online, only to discover the package contains a vengeful ghost.", "image_url": "https://covers.openlibrary.org/b/isbn/9780061914171-L.jpg", "price": 15.00, "rating": 4.5, "queue_list": []},
      {"title": "The Cabin at the End of the World", "author": "Paul Tremblay", "category": "Horror", "isbn": "9780062679116", "available": 2, "description": "A peaceful vacation gets interrupted by four strangers demanding an impossible choice to avert Armageddon.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062679116-L.jpg", "price": 14.95, "rating": 4.3, "queue_list": []},

      # === NON-FICTION (5 Books) ===
      {"title": "Sapiens", "author": "Yuval Noah Harari", "category": "Non-Fiction", "isbn": "9780062316097", "available": 7, "description": "A retrospective tracking how an insignificant ape became master of Earth through shared fiction.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg", "price": 24.99, "rating": 4.8, "queue_list": []},
      {"title": "Atomic Habits", "author": "James Clear", "category": "Non-Fiction", "isbn": "9780735211292", "available": 12, "description": "The definitive strategic framework on behavior modification using minor 1% daily adjustments.", "image_url": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg", "price": 17.00, "rating": 4.9, "queue_list": []},
      {"title": "The Power of Habit", "author": "Charles Duhigg", "category": "Non-Fiction", "isbn": "9781400069286", "available": 5, "description": "Investigating the neurological loop behind behavior patterns, explaining how they can be broken.", "image_url": "https://covers.openlibrary.org/b/isbn/9781400069286-L.jpg", "price": 16.00, "rating": 4.7, "queue_list": []},
      {"title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "category": "Non-Fiction", "isbn": "9780374275631", "available": 4, "description": "An audit isolating the two parallel mental systems that govern human choices: instinct versus slow logic.", "image_url": "https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg", "price": 18.00, "rating": 4.6, "queue_list": []},
      {"title": "Quiet", "author": "Susan Cain", "category": "Non-Fiction", "isbn": "9780307352156", "available": 3, "description": "Our culture dramatically undervalues introverts, charts how much we lose in doing so.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg", "price": 15.99, "rating": 4.7, "queue_list": []},

      # === MYSTERY (15 Books) ===
      {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "category": "Mystery", "isbn": "9780307269751", "available": 4, "description": "A financial journalist teams up with a punk computer hacker to solve a decades-old disappearance.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg", "price": 14.95, "rating": 4.7, "queue_list": []},
      {"title": "And Then There Were None", "author": "Agatha Christie", "category": "Mystery", "isbn": "9780062073488", "available": 5, "description": "Ten structural strangers are lured out to an isolated island mansion and executed one-by-one.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg", "price": 12.99, "rating": 4.8, "queue_list": []},
      {"title": "Gone Girl", "author": "Gillian Flynn", "category": "Mystery", "isbn": "9780307588371", "available": 3, "description": "When a beautiful wife vanishes on her anniversary, her husband becomes the center of suspicion.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg", "price": 15.00, "rating": 4.5, "queue_list": []},
      {"title": "The Silent Patient", "author": "Alex Michaelides", "category": "Mystery", "isbn": "9781250301697", "available": 3, "description": "A famous painter shoots her husband and refuses to utter a word, provoking a therapist's obsession.", "image_url": "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg", "price": 16.99, "rating": 4.6, "queue_list": []},
      {"title": "The Da Vinci Code", "author": "Dan Brown", "category": "Mystery", "isbn": "9780307474278", "available": 6, "description": "A high-stakes symbology chase through Paris museum crime scenes, decoding cryptic riddles.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg", "price": 13.99, "rating": 4.4, "queue_list": []},
      {"title": "Too Late", "author": "Colleen Hoover", "category": "Mystery", "isbn": "9781538756577", "available": 2, "description": "A dark psychological drama detailing a woman caught in a dangerous relationship with a drug trafficker.", "image_url": "https://covers.openlibrary.org/b/isbn/9781538756577-L.jpg", "price": 13.99, "rating": 4.4, "queue_list": []},
      {"title": "The Outsider", "author": "Stephen King", "category": "Mystery", "isbn": "9781501180989", "available": 3, "description": "An unspeakable crime points to a coach. Conflicting forensic evidence proves he was in two places at once.", "image_url": "https://covers.openlibrary.org/b/isbn/9781501180989-L.jpg", "price": 17.99, "rating": 4.7, "queue_list": []},
      {"title": "The Woman in the Window", "author": "A.J. Finn", "category": "Mystery", "isbn": "9780062678416", "available": 3, "description": "An agoraphobic psychologist spies on neighbors, until she looks through her lens and witnesses a crime.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062678416-L.jpg", "price": 13.99, "rating": 4.5, "queue_list": []},
      {"title": "The Maidens", "author": "Alex Michaelides", "category": "Mystery", "isbn": "9781250274168", "available": 5, "description": "A therapist becomes obsessed with proving a charismatic tragedy professor at Cambridge is a serial killer.", "image_url": "https://covers.openlibrary.org/b/isbn/9781250274168-L.jpg", "price": 16.99, "rating": 4.4, "queue_list": []},
      {"title": "The Paris Apartment", "author": "Lucy Foley", "category": "Mystery", "isbn": "9780063003057", "available": 3, "description": "Jess breaks her routine to visit her half-brother in his luxury Paris apartment, but when she arrives, he is missing.", "image_url": "https://covers.openlibrary.org/b/isbn/9780063003057-L.jpg", "price": 16.00, "rating": 4.3, "queue_list": []},
      {"title": "The Murder of Roger Ackroyd", "author": "Agatha Christie", "category": "Mystery", "isbn": "9780062073563", "available": 4, "description": "Hercule Poirot comes out of retirement to solve an intricate, layered village murder with a massive twist ending.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062073563-L.jpg", "price": 12.99, "rating": 4.9, "queue_list": []},
      {"title": "In the Woods", "author": "Tana French", "category": "Mystery", "isbn": "9780143113492", "available": 3, "description": "A Dublin detective investigates a child murder near an archaeological site that closely mirrors his own dark childhood trauma.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg", "price": 14.99, "rating": 4.6, "queue_list": []},
      {"title": "The Alienist", "author": "Caleb Carr", "category": "Mystery", "isbn": "9780345417015", "available": 2, "description": "In 1896 New York, a reporter, a psychologist, and a police commissioner use early forensics to track a serial killer.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345417015-L.jpg", "price": 15.50, "rating": 4.7, "queue_list": []},
      {"title": "The Word Is Murder", "author": "Anthony Horowitz", "category": "Mystery", "isbn": "9780062676832", "available": 4, "description": "A wealthy woman arranges her own funeral setup, only to be strangled six hours later, prompting a complex modern detective investigation.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062676832-L.jpg", "price": 13.99, "rating": 4.5, "queue_list": []},
      {"title": "Magpie Murders", "author": "Anthony Horowitz", "category": "Mystery", "isbn": "9780062645234", "available": 3, "description": "An editor reads a detective manuscript, finding an intricate mystery within a mystery that conceals a real crime.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062645234-L.jpg", "price": 16.50, "rating": 4.6, "queue_list": []},

      # === ROMANCE (11 Books) ===
      {"title": "Pride and Prejudice", "author": "Jane Austen", "category": "Romance", "isbn": "9780141439518", "available": 5, "description": "The classic romantic clash between opinionated Elizabeth Bennet and proud Mr. Darcy.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg", "price": 7.99, "rating": 4.8, "queue_list": []},
      {"title": "The Fault in Our Stars", "author": "John Green", "category": "Romance", "isbn": "9780525478812", "available": 4, "description": "Two cancer-afflicted teenagers meet in a support group, striking a connection that redefines their outlook.", "image_url": "https://covers.openlibrary.org/b/isbn/9780525478812-L.jpg", "price": 11.99, "rating": 4.7, "queue_list": []},
      {"title": "Me Before You", "author": "Jojo Moyes", "category": "Romance", "isbn": "9780143124542", "available": 3, "description": "An eccentric small-town girl takes an assistive care job for a cynical billionaire paralyzed from an accident.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg", "price": 14.00, "rating": 4.6, "queue_list": []},
      {"title": "Normal People", "author": "Sally Rooney", "category": "Romance", "isbn": "9781984822178", "available": 5, "description": "Tracking the complex social relationship of Connell and Marianne as they drift across university years.", "image_url": "https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg", "price": 16.95, "rating": 4.3, "queue_list": []},
      {"title": "The Notebook", "author": "Nicholas Sparks", "category": "Romance", "isbn": "9780446605236", "available": 4, "description": "An epic love story read aloud from a faded notebook to a woman navigating memory loss.", "image_url": "https://covers.openlibrary.org/b/isbn/9780446605236-L.jpg", "price": 10.99, "rating": 4.7, "queue_list": []},
      {"title": "Book Lovers", "author": "Emily Henry", "category": "Romance", "isbn": "9780593334836", "available": 5, "description": "A cutthroat literary agent and an editor find themselves in the same small town over a summer.", "image_url": "https://covers.openlibrary.org/b/isbn/9780593334836-L.jpg", "price": 15.00, "rating": 4.7, "queue_list": []},
      {"title": "The Love Hypothesis", "author": "Ali Hazelwood", "category": "Romance", "isbn": "9780593336823", "available": 6, "description": "A Ph.D. candidate fakes a relationship with a cold, notorious professor to prove her career path viability.", "image_url": "https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg", "price": 14.99, "rating": 4.6, "queue_list": []},
      {"title": "Beach Read", "author": "Emily Henry", "category": "Romance", "isbn": "9781984806734", "available": 4, "description": "Two rival authors with writer's block challenge each other to write in each other's distinct genres over a summer.", "image_url": "https://covers.openlibrary.org/b/isbn/978198406734-L.jpg", "price": 13.99, "rating": 4.5, "queue_list": []},
      {"title": "Jane Eyre", "author": "Charlotte Brontë", "category": "Romance", "isbn": "9780141441146", "available": 3, "description": "An orphaned governess finds independence and deep romantic tension inside an estate with a dark mansion secret.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg", "price": 8.99, "rating": 4.8, "queue_list": []},
      {"title": "Wuthering Heights", "author": "Emily Brontë", "category": "Romance", "isbn": "9780141439556", "available": 3, "description": "The turbulent, passionate, and destructive history of Heathcliff and Catherine Earnshaw on the Yorkshire moors.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg", "price": 7.50, "rating": 4.4, "queue_list": []},
      {"title": "Sense and Sensibility", "author": "Jane Austen", "category": "Romance", "isbn": "9780141439662", "available": 4, "description": "The romantic trials of the Dashwood sisters as they balance practical reason with intense emotional sensitivity.", "image_url": "https://covers.openlibrary.org/b/isbn/9780141439662-L.jpg", "price": 8.50, "rating": 4.6, "queue_list": []},

      # === THRILLER (13 Books) ===
      {"title": "Shutter Island", "author": "Dennis Lehane", "category": "Thriller", "isbn": "9780062111814", "available": 3, "description": "A US Marshal travels to an island mental facility to investigate an impossible secure ward disappearance.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062111814-L.jpg", "price": 14.99, "rating": 4.7, "queue_list": []},
      {"title": "The Girl on the Train", "author": "Paula Hawkins", "category": "Thriller", "isbn": "9781594633669", "available": 4, "description": "An alcoholic commuter catches a shocking glimpse of a domestic incident through her train window.", "image_url": "https://covers.openlibrary.org/b/isbn/9781594633669-L.jpg", "price": 15.99, "rating": 4.3, "queue_list": []},
      {"title": "The Guest List", "author": "Lucy Foley", "category": "Thriller", "isbn": "9780062868824", "available": 4, "description": "A glamorous wedding on an isolated Irish coast turns deadly when a corpse is discovered.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062868824-L.jpg", "price": 16.99, "rating": 4.4, "queue_list": []},
      {"title": "The Couple Next Door", "author": "Shari Lapena", "category": "Thriller", "isbn": "9780143110439", "available": 2, "description": "A domestic dinner party next door turns into a nightmare when a baby vanishes from her crib.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143110439-L.jpg", "price": 13.99, "rating": 4.5, "queue_list": []},
      {"title": "The Kind Worth Killing", "author": "Peter Swanson", "category": "Thriller", "isbn": "9780062267535", "available": 3, "description": "Two strangers form a dark pact on a flight to execute a deceptive spouse, initiating a lethal game.", "image_url": "https://covers.openlibrary.org/b/isbn/9780062267535-L.jpg", "price": 14.50, "rating": 4.6, "queue_list": []},
      {"title": "The Housemaid", "author": "Freida McFadden", "category": "Thriller", "isbn": "9781837901241", "available": 4, "description": "Every day I clean the house. I eat alone. But I find out that the door to my room only locks from the outside.", "image_url": "https://covers.openlibrary.org/b/id/14745848-L.jpg", "price": 12.99, "rating": 4.8, "queue_list": []},
      {"title": "The Inmate", "author": "Freida McFadden", "category": "Thriller", "isbn": "9781837901265", "available": 3, "description": "A nurse takes a job where the man who tried to murder her decades ago is serving a life sentence.", "image_url": "https://covers.openlibrary.org/b/isbn/9781837901265-L.jpg", "price": 13.50, "rating": 4.6, "queue_list": []},
      {"title": "The Teacher", "author": "Freida McFadden", "category": "Thriller", "isbn": "9781837902699", "available": 5, "description": "A dark high-school mystery focusing on a teacher, her husband, and a student whose secrets threaten them.", "image_url": "https://covers.openlibrary.org/b/isbn/9781837902699-L.jpg", "price": 14.99, "rating": 4.7, "queue_list": []},
      {"title": "Verity", "author": "Colleen Hoover", "category": "Thriller", "isbn": "9781791392796", "available": 6, "description": "An author is hired to finish an injured writer's books, discovering an autobiography with chilling secrets.", "image_url": "https://covers.openlibrary.org/b/isbn/9781791392796-L.jpg", "price": 15.99, "rating": 4.8, "queue_list": []},
      {"title": "Rock Paper Scissors", "author": "Alice Feeney", "category": "Thriller", "isbn": "9781250273840", "available": 4, "description": "A couple wins a trip to Scotland to save their marriage—but someone is lying, and the trip turns fatal.", "image_url": "https://covers.openlibrary.org/b/isbn/9781250273840-L.jpg", "price": 14.50, "rating": 4.6, "queue_list": []},
      {"title": "Sharp Objects", "author": "Gillian Flynn", "category": "Thriller", "isbn": "9780307341556", "available": 2, "description": "Reporter Camille Preaker must return to her tiny hometown to cover the jagged, unsolved murders of two young girls.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307341556-L.jpg", "price": 11.99, "rating": 4.7, "queue_list": []},
      {"title": "None of This is True", "author": "Lisa Jewell", "category": "Thriller", "isbn": "9781982179007", "available": 4, "description": "A podcaster starts a series on an unassuming woman, unaware she is letting a dangerous psychopath into her life.", "image_url": "https://covers.openlibrary.org/b/isbn/9781982179007-L.jpg", "price": 17.50, "rating": 4.8, "queue_list": []},
      {"title": "The Autumn Vault", "author": "Lisa Jewell", "category": "Thriller", "isbn": "9781501190100", "available": 4, "description": "A woman inherits a multi-million dollar mansion where she was found as a baby alongside three dead bodies.", "image_url": "https://covers.openlibrary.org/b/isbn/9781501190100-L.jpg", "price": 15.00, "rating": 4.6, "queue_list": []},

      # === BIOGRAPHY (5 Books) ===
      {"title": "Steve Jobs", "author": "Walter Isaacson", "category": "Biography", "isbn": "9781451648539", "available": 5, "description": "The definitive look at the Silicon Valley visionary who revolutionized computing, music, and mobile tech.", "image_url": "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg", "price": 20.00, "rating": 4.8, "queue_list": []},
      {"title": "Becoming", "author": "Michelle Obama", "category": "Biography", "isbn": "9781524763138", "available": 6, "description": "An intimate account tracking the experiences that carved the first African American First Lady.", "image_url": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg", "price": 18.99, "rating": 4.8, "queue_list": []},
      {"title": "Elon Musk", "author": "Walter Isaacson", "category": "Biography", "isbn": "9781982181284", "available": 4, "description": "The inside look into the hyper-intense entrepreneur who propelled global shifts toward EVs and space flight.", "image_url": "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg", "price": 24.00, "rating": 4.6, "queue_list": []},
      {"title": "Shoe Dog", "author": "Phil Knight", "category": "Biography", "isbn": "9781501135910", "available": 5, "description": "The candid memoir of Nike's founder, mapping the chaotic start-up phases that forged a sports empire.", "image_url": "https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg", "price": 16.99, "rating": 4.9, "queue_list": []},
      {"title": "Open", "author": "Andre Agassi", "category": "Biography", "isbn": "9780307388407", "available": 3, "description": "An unvarnished look into a tennis superstar who achieved peak standings while secretly harboring resentment for the sport.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307388407-L.jpg", "price": 15.00, "rating": 4.8, "queue_list": []},

      # === HISTORY (11 Books) ===
      {"title": "The Guns of August", "author": "Barbara W. Tuchman", "category": "History", "isbn": "9780345386236", "available": 3, "description": "The Pulitzer Prize-winning breakdown of the diplomatic collapses that catalyzed World War I.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345386236-L.jpg", "price": 15.99, "rating": 4.8, "queue_list": []},
      {"title": "SPQR: A History of Ancient Rome", "author": "Mary Beard", "category": "History", "isbn": "9781631492426", "available": 4, "description": "An analytical retrospective exploring how a backwater village transformed into an expansive empire.", "image_url": "https://covers.openlibrary.org/b/isbn/9781631492426-L.jpg", "price": 19.95, "rating": 4.7, "queue_list": []},
      {"title": "Team of Rivals", "author": "Doris Kearns Goodwin", "category": "History", "isbn": "9780684824901", "available": 2, "description": "The biographical tracking of Lincoln's genius in assembling a cabinet entirely composed of fierce rivals.", "image_url": "https://covers.openlibrary.org/b/isbn/9780684824901-L.jpg", "price": 21.00, "rating": 4.9, "queue_list": []},
      {"title": "The Wright Brothers", "author": "David McCullough", "category": "History", "isbn": "9781476728759", "available": 4, "description": "The dramatic history of the two self-taught mechanics from Ohio who systematically solved human flight.", "image_url": "https://covers.openlibrary.org/b/isbn/9781476728759-L.jpg", "price": 16.99, "rating": 4.8, "queue_list": []},
      {"title": "The Rise and Fall of the Third Reich", "author": "William L. Shirer", "category": "History", "isbn": "9781451651683", "available": 2, "description": "The absolute classic historical catalog tracing totalitarian power networks in Europe.", "image_url": "https://covers.openlibrary.org/b/isbn/9781451651683-L.jpg", "price": 25.00, "rating": 4.7, "queue_list": []},
      {"title": "Guns, Germs, and Steel", "author": "Jared Diamond", "category": "History", "isbn": "9780393317558", "available": 4, "description": "Articulating the geographic and environmental parameters that shaped global empire development trends.", "image_url": "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg", "price": 18.99, "rating": 4.8, "queue_list": []},
      {"title": "The Silk Roads", "author": "Peter Frankopan", "category": "History", "isbn": "9781101912379", "available": 5, "description": "Shifting global historical perspectives eastward to track the trade routes that formed the spine of Asia.", "image_url": "https://covers.openlibrary.org/b/isbn/9781101912379-L.jpg", "price": 20.00, "rating": 4.6, "queue_list": []},
      {"title": "1776", "author": "David McCullough", "author": "David McCullough", "category": "History", "isbn": "9780743226721", "available": 3, "description": "The intense timeline chronicling the military operational parameters of the American Revolutionary forces under Washington.", "image_url": "https://covers.openlibrary.org/b/isbn/9780743226721-L.jpg", "price": 16.95, "rating": 4.8, "queue_list": []},
      {"title": "The Plantagenets", "author": "Dan Jones", "category": "History", "isbn": "9780143124252", "available": 4, "description": "The epic architectural history of the fierce royal dynasty that forged the absolute foundations of England.", "image_url": "https://covers.openlibrary.org/b/isbn/9780143124252-L.jpg", "price": 17.50, "rating": 4.7, "queue_list": []},
      {"title": "A History of the World in 6 Glasses", "author": "Tom Standage", "category": "History", "isbn": "9780802715524", "available": 4, "description": "Tracking human civilization milestones through the lens of six iconic fluids: beer, wine, spirits, coffee, tea, and cola.", "image_url": "https://covers.openlibrary.org/b/isbn/9780802715524-L.jpg", "price": 13.99, "rating": 4.5, "queue_list": []},
      {"title": "The Crusades", "author": "Thomas Asbridge", "category": "History", "isbn": "9780060787295", "available": 2, "description": "An exhaustive, unvarnished tracking of the religious wars fought for ultimate control over holy territories.", "image_url": "https://covers.openlibrary.org/b/isbn/9780060787295-L.jpg", "price": 22.00, "rating": 4.7, "queue_list": []},

      # === SCIENCE (13 Books) ===
      {"title": "A Brief History of Time", "author": "Stephen Hawking", "category": "Science", "isbn": "9780553380163", "available": 6, "description": "The physics classic introducing general readers to cosmic concepts like the Big Bang and quantum gravity.", "image_url": "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg", "price": 16.00, "rating": 4.9, "queue_list": []},
      {"title": "Cosmos", "author": "Carl Sagan", "category": "Science", "isbn": "9780345539434", "available": 5, "description": "A poetic tracking of cosmic exploration, exploring our relationship with the spatial ocean.", "image_url": "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg", "price": 15.00, "rating": 4.9, "queue_list": []},
      {"title": "The Selfish Gene", "author": "Richard Dawkins", "category": "Science", "isbn": "9780198788607", "available": 4, "description": "A perspective framing biological organisms as evolutionary survival vessels built to preserve genes.", "image_url": "https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg", "price": 14.95, "rating": 4.6, "queue_list": []},
      {"title": "Astrophysics for People in a Hurry", "author": "Neil deGrasse Tyson", "category": "Science", "isbn": "9780393609394", "available": 8, "description": "A quick scientific digest breaking down the physics laws governing matter and spatial boundaries.", "image_url": "https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg", "price": 12.95, "rating": 4.7, "queue_list": []},
      {"title": "The Elegant Universe", "author": "Brian Greene", "category": "Science", "isbn": "9780393338102", "available": 3, "description": "An accessible deep dive into String Theory, explaining how vibrating fibers resolve conflicts in physics models.", "image_url": "https://covers.openlibrary.org/b/isbn/9780393338102-L.jpg", "price": 16.95, "rating": 4.7, "queue_list": []},
      {"title": "Brief Answers to Big Questions", "author": "Stephen Hawking", "category": "Science", "isbn": "9781524797096", "available": 5, "description": "The final blueprint addressing humanity's queries regarding cosmic origins and spatial survival.", "image_url": "https://covers.openlibrary.org/b/isbn/9781524797096-L.jpg", "price": 16.99, "rating": 4.8, "queue_list": []},
      {"title": "The Gene: An Intimate History", "author": "Siddhartha Mukherjee", "category": "Science", "isbn": "9781476733524", "available": 4, "description": "A brilliant synthesis documenting the historical tracking, manipulation, and moral ethics of human genetic blueprints.", "image_url": "https://covers.openlibrary.org/b/isbn/9781476733524-L.jpg", "price": 19.99, "rating": 4.8, "queue_list": []},
      {"title": "What If?", "author": "Randall Munroe", "category": "Science", "isbn": "9780544272996", "available": 6, "description": "Serious scientific analysis answers to absurd hypothetical questions from the creator of the popular webcomic xkcd.", "image_url": "https://covers.openlibrary.org/b/isbn/9780544272996-L.jpg", "price": 15.00, "rating": 4.7, "queue_list": []},
      {"title": "The Hidden Life of Trees", "author": "Peter Wohlleben", "category": "Science", "isbn": "9781771642484", "available": 5, "description": "Sharing the deep botanical science behind forest communication arrays via underground fungal network roots.", "image_url": "https://covers.openlibrary.org/b/isbn/9781771642484-L.jpg", "price": 14.95, "rating": 4.6, "queue_list": []},
      {"title": "Sapiens: A Graphic History", "author": "Yuval Noah Harari", "category": "Science", "isbn": "9780063051331", "available": 3, "description": "The radical transformation of human history adapted into an accessible, beautifully illustrated scientific narrative engine.", "image_url": "https://covers.openlibrary.org/b/isbn/9780063051331-L.jpg", "price": 21.00, "rating": 4.6, "queue_list": []},
      {"title": "The Omnivore's Dilemma", "author": "Michael Pollan", "category": "Science", "isbn": "9781594200823", "available": 4, "description": "An ecological and biological tracking of human food chains, uncovering the environmental costs of eating parameters.", "image_url": "https://covers.openlibrary.org/b/isbn/9781594200823-L.jpg", "price": 16.00, "rating": 4.5, "queue_list": []},
      {"title": "Incognito: Secret Lives of Brain", "author": "David Eagleman", "category": "Science", "isbn": "9780307377333", "available": 4, "description": "A compelling deep dive exploring the subterranean neuro-science layers that control choices beneath active consciousness.", "image_url": "https://covers.openlibrary.org/b/isbn/9780307377333-L.jpg", "price": 15.50, "rating": 4.7, "queue_list": []},
      {"title": "The Emperor of All Maladies", "author": "Siddhartha Mukherjee", "category": "Science", "isbn": "9781439170915", "available": 3, "description": "The complete biography of cancer, tracking human medical engineering struggles to decode and eradicate cellular adaptation anomalies.", "image_url": "https://covers.openlibrary.org/b/isbn/9781439170915-L.jpg", "price": 20.00, "rating": 4.9, "queue_list": []}
    ]

    print(f"📦 Injecting exactly {len(master_book_list)} balanced catalog assets into Atlas...")
    books_collection.insert_many(master_book_list)
    print("🚀 Execution complete. 100 high-resolution volumes registered cleanly inside MongoDB Atlas.")

except Exception as error:
    print(f"❌ Connection Blocked: {error}")